* Random notes:
** ev name
** ev date
** ev format
** no of records
** gender
** category
** sub category
** cost
* Things i installed
#+begin_quote

pip install Jinja2
pip install simple-http-server-jinja
pip instlal python-lsp-server
pip install pandas
pip install tabulate
pip install openpyxl
pip install Flask
pip install Flask-SQLAlchemy
pip install Flask-Migrate
flask_jwt_extended
flask_bcrypt
psycopg2_binary


#+end_quote
* TODO

create and run an app from code

add a database config, for URI for the sqlalchemy

as part of the processing of the POST request, we assign it to a variable each, then create an object instance of our favourite object

using alchemy, we then commit this new object
* advantages of excel over database
** easy for him
** he can easily create a dropdown himself
** he can use his helper functions to easily view specific events at will
* advantages of database over excel
** more predictable in thesystem
** easy to ensure data integrity, of something happens such as a connection problem right when the user registers 
** we have to ask him, if he changes tae category all tae time
*** if sometimes this might be more ticky than usual
** if the above is true, this means we either:
*** create a specific "data entry" form just for him
*** he retains the Excel workfow, and i have to think of uploading it to database
* we have to read on this:
** https://trumpexcel.com/extract-data-from-drop-down-list/
* Explain:
** Show the mapping, and why this makes it easy for first time bulk upload. But its tied to filename
** Show the FIDE check feature, it checks if number fields should be numbers
** show all duplicates error, of each file
* unique ID:
** MCFID+yearofbirth
* FIDE rating:
** 1400 - 2800
** or 0 or ''
* Upload
** https://trumpexcel.com/extract-data-from-drop-down-list/
* Tests:
** Test to make sure mcf and frl.csv files are deleted everytime
** Password
#+begin_quote

220400066
2010

220300012
2006

220400014
2011

220300012
2006

#+end_quote
** Events
#+begin_quote

MCF Office Blitz Q1 2025
Malaysian Chess Amateur Championship
National Interstate Chess Championship


#+end_quote
** Event expiry flow should not create dangling data
*** create event
*** member 1 registers event
*** create form
*** member 1 registers event
*** member 2 registers event
*** member RE-registers event
*** we expire event,
*** member 3 registers event, gets soft warning
*** member 1 checks his page, no problems
** 2nd variation
* Video:
** All the processes from the video
** Show wrongly uploading a video
** Test if the same file is uploaded
** Its simple, 2 types of uploads MCF file, if youre afraid of over-writing anything, use insert. If not, use update. It overwrites based on MCF ID, nothing else.
** Theres only FRL inserts, becoz FRL are "updates" in nature. (subservient/dependent on existing MCF record).
** Registering for an event
** Show removing events registered
** Showing logging in
** Showing dropdown download
* Form creation test:
| form     | field       | value                           | type     |
|----------+-------------+---------------------------------+----------|
| Q1 event | date        | M                               | datetime |
| Q1 event | gender      | M                               | dropdown |
| Q1 event | gender      | F                               | dropdown |
| Q1 event | gender      | Open                            | dropdown |
| Q1 event | description | "a KL based event for under 18" | text     |
* Form questions:
** National Youth Chess Championship 2024
** hold harmless agreement
*** This is to confirm I have read and understood the regulations
*** 
** please provide full IC name
** Are you a PARA/OKU player
*** Please 
** As this event caters for under-18,pleae obtain permission from parents. I hereby confirm that Im allowing my child to participiate in this event. 
** Please provide full guardia name
** please provide guardian IC
** please provide guardian email address
** I hereby agree to not hold the management accountable to any loss or damage
** The entrry is fixed at RM 60 regardless of age, or rating. Please choose an event:
*** open event
*** girls event
** please choose an age category
*** under-8
*** under-18
** Please upload proof of payment (RM 60)


* Things to present:
** DONE All negative checks passed so far, such as pressing upload when no file is chosen (both for member_front & admin page)
** DONE right now form is not atthced a single event. Mostly testing dynamic question creation
** DONE show download CSV feature
** DONE Reassure Terry: screenshot "tasksI do daily" in meeting_docs
** space blocks in field
** download feature for event answers (download name as event name too)
** checks mimetype, to ensure users dont upload random filetypes, and not just extension
** file input now works, some different folder structure, and some disabled elements depending on subgroup or non-subgroup
** show subgrouip answers page, and its relevant download feature
** DONE show error of "no form for this event"
** DONE full blown question flow like National Youth Chess Championship 2024, also include checks of spaces in subgroup fieldname, and missing subgroup fieldname
** DONE show the upload folder structure created (path nameand filename), especially when uploading 2 files
** show that repeated file uploads dont clash, thanks to date, show the upload_logs page
** DONE remind Terry that the way event expiry is setup, you MUST backup/download users form answers, before expiring the event, coz all related entities are deleted for real. The only difference between DELETED and EXPIRED event is EXPIRED event is stored in its own table, and user gets a soft warning, when attempting to register. Show the flow of expiring an event. Which is triggered upon creation of event. show the message the user gets.
** NOT present, but rather reminder that soft-deleted events essentially serve special purpose in the business logic.
* Some limitations:
** subgroupsof questions cannot be tied to each answer, the logic is now to be complicated. It can only be tied to a question
** this means Questions like:
#+begin_quote

PLEASE SELECT YOUR ENTRY STATUS *
I have a chess title - IM / WIM / NM / WNM
I am representing my state
I am an Open Entry

#+end_quote
** will have to be dividede to 3:
**
#+begin_quote

Your entry status, I have a chess title - IM / WIM / NM / WNM
Your entry status, I am representing my state
Your entry status, I am an Open Entry


#+end_quote
** and it will only be limited to a single radio button (and values: selected or on-selectd)
