"""empty message

Revision ID: 00de22c8141a
Revises: 864831116014
Create Date: 2025-03-27 15:55:01.631564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00de22c8141a'
down_revision = '864831116014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.drop_constraint('fide_mcfId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['mcfId'], ['mcfId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fide_mcfId_fkey', 'member', ['mcfId'], ['mcfId'])

    # ### end Alembic commands ###
