"""empty message

Revision ID: 17ff5a5716a2
Revises: b2f3a19d27d0
Create Date: 2025-03-16 22:35:41.565863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ff5a5716a2'
down_revision = 'b2f3a19d27d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('mcfId', sa.Integer(), nullable=False),
    sa.Column('mcfName', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('yearOfBirth', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('nationalRating', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('mcfId')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_mcfName'), ['mcfName'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_nationalRating'), ['nationalRating'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_yearOfBirth'), ['yearOfBirth'], unique=False)

    op.create_table('event_members',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.mcfId'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_members')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_yearOfBirth'))
        batch_op.drop_index(batch_op.f('ix_member_state'))
        batch_op.drop_index(batch_op.f('ix_member_nationalRating'))
        batch_op.drop_index(batch_op.f('ix_member_mcfName'))
        batch_op.drop_index(batch_op.f('ix_member_gender'))

    op.drop_table('member')
    # ### end Alembic commands ###
