"""empty message

Revision ID: 218ad878a983
Revises: 19ac3eb5def8
Create Date: 2025-03-16 20:02:54.765090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218ad878a983'
down_revision = '19ac3eb5def8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index('ix_member_gender')
        batch_op.drop_index('ix_member_mcfName')
        batch_op.drop_index('ix_member_nationalRating')
        batch_op.drop_index('ix_member_state')
        batch_op.drop_index('ix_member_yearOfBirth')

    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('mcfId', sa.INTEGER(), nullable=False),
    sa.Column('mcfName', sa.VARCHAR(length=128), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=64), nullable=False),
    sa.Column('yearOfBirth', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state', sa.VARCHAR(length=64), nullable=False),
    sa.Column('nationalRating', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('mcfId')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index('ix_member_yearOfBirth', ['yearOfBirth'], unique=False)
        batch_op.create_index('ix_member_state', ['state'], unique=False)
        batch_op.create_index('ix_member_nationalRating', ['nationalRating'], unique=False)
        batch_op.create_index('ix_member_mcfName', ['mcfName'], unique=False)
        batch_op.create_index('ix_member_gender', ['gender'], unique=False)

    # ### end Alembic commands ###
