"""empty message

Revision ID: 365dfd486490
Revises: b313ec66daf1
Create Date: 2025-03-31 17:15:04.341437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365dfd486490'
down_revision = 'b313ec66daf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
