"""empty message

Revision ID: 3f37bf7d3993
Revises: 6629fe1d7428
Create Date: 2025-04-03 21:40:17.830801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f37bf7d3993'
down_revision = '6629fe1d7428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('fideId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('fideId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
