"""empty message

Revision ID: 6629fe1d7428
Revises: 365dfd486490
Create Date: 2025-04-03 21:36:17.472506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6629fe1d7428'
down_revision = '365dfd486490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.drop_index('ix_fide_fideRating')

    op.drop_table('fide')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fideId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fideName', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('fideRating', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_member_fideRating'), ['fideRating'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_fideRating'))
        batch_op.drop_column('fideRating')
        batch_op.drop_column('fideName')
        batch_op.drop_column('fideId')

    op.create_table('fide',
    sa.Column('fideId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fideName', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('fideRating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mcfId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mcfId'], ['member.mcfId'], name='fide_mcfId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fideId', name='fide_pkey')
    )
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.create_index('ix_fide_fideRating', ['fideRating'], unique=False)

    # ### end Alembic commands ###
