"""empty message

Revision ID: 67d59a4ea368
Revises: b799ded3641b
Create Date: 2025-04-20 23:44:58.471501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d59a4ea368'
down_revision = 'b799ded3641b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_tournamentName')
        batch_op.create_index(batch_op.f('ix_events_tournamentName'), ['tournamentName'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tournamentName'))
        batch_op.create_index('ix_events_tournamentName', ['tournamentName'], unique=True)

    # ### end Alembic commands ###
