"""empty message

Revision ID: 6f9e9a98ce2b
Revises: 4b97e0b5cc9f
Create Date: 2025-04-26 01:07:44.231151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9e9a98ce2b'
down_revision = '4b97e0b5cc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('mcfId',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('nextval(\'"members_mcfId_seq"\'::regclass)'))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('mcfId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('nextval(\'"members_mcfId_seq"\'::regclass)'))

    # ### end Alembic commands ###
