"""empty message

Revision ID: 864831116014
Revises: f82488e4c409
Create Date: 2025-03-25 16:35:09.785856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864831116014'
down_revision = 'f82488e4c409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcfId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['mcfId'], ['mcfId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mcfId')

    # ### end Alembic commands ###
