"""empty message

Revision ID: 92f05fb95060
Revises: 218ad878a983
Create Date: 2025-03-16 20:49:17.899812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f05fb95060'
down_revision = '218ad878a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_discipline')
        batch_op.drop_index('ix_event_endDate')
        batch_op.drop_index('ix_event_startDate')
        batch_op.drop_index('ix_event_tournamentName')

    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournamentName', sa.VARCHAR(length=128), nullable=False),
    sa.Column('startDate', sa.VARCHAR(length=64), nullable=False),
    sa.Column('endDate', sa.VARCHAR(length=64), nullable=False),
    sa.Column('discipline', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_tournamentName', ['tournamentName'], unique=1)
        batch_op.create_index('ix_event_startDate', ['startDate'], unique=False)
        batch_op.create_index('ix_event_endDate', ['endDate'], unique=False)
        batch_op.create_index('ix_event_discipline', ['discipline'], unique=False)

    # ### end Alembic commands ###
