"""empty message

Revision ID: a5c720b3de83
Revises: f4238c2834ef
Create Date: 2025-04-26 01:00:05.539868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c720b3de83'
down_revision = 'f4238c2834ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('mcfId',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('mcfId',
               existing_type=sa.String(length=255),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
