"""empty message

Revision ID: b313ec66daf1
Revises: 17ff5a5716a2
Create Date: 2025-03-29 18:15:48.519633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b313ec66daf1'
down_revision = '17ff5a5716a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['mcfId'], ['mcfId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fide', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
