"""empty message

Revision ID: b799ded3641b
Revises: 427b4126ddeb
Create Date: 2025-04-06 14:18:55.967157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b799ded3641b'
down_revision = '427b4126ddeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournamentName', sa.String(length=128), nullable=True),
    sa.Column('startDate', sa.String(length=64), nullable=True),
    sa.Column('endDate', sa.String(length=64), nullable=True),
    sa.Column('discipline', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_discipline'), ['discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_endDate'), ['endDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_startDate'), ['startDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tournamentName'), ['tournamentName'], unique=True)

    op.create_table('members',
    sa.Column('mcfId', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('mcfName', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('yearOfBirth', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('nationalRating', sa.String(length=64), nullable=True),
    sa.Column('events', sa.String(length=300), nullable=True),
    sa.Column('fideId', sa.Integer(), nullable=True),
    sa.Column('fideName', sa.String(length=80), nullable=True),
    sa.Column('fideRating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mcfId')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_events'), ['events'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_fideRating'), ['fideRating'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_mcfName'), ['mcfName'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_nationalRating'), ['nationalRating'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_yearOfBirth'), ['yearOfBirth'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_yearOfBirth'))
        batch_op.drop_index(batch_op.f('ix_members_state'))
        batch_op.drop_index(batch_op.f('ix_members_nationalRating'))
        batch_op.drop_index(batch_op.f('ix_members_mcfName'))
        batch_op.drop_index(batch_op.f('ix_members_gender'))
        batch_op.drop_index(batch_op.f('ix_members_fideRating'))
        batch_op.drop_index(batch_op.f('ix_members_events'))

    op.drop_table('members')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tournamentName'))
        batch_op.drop_index(batch_op.f('ix_events_startDate'))
        batch_op.drop_index(batch_op.f('ix_events_endDate'))
        batch_op.drop_index(batch_op.f('ix_events_discipline'))

    op.drop_table('events')
    # ### end Alembic commands ###
